ALTER TABLE prices DROP COLUMN barcode;

CREATE TABLE IF NOT EXISTS barcodes(
	id INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	price_id INTEGER UNSIGNED,
	value VARCHAR(127) DEFAULT "" UNIQUE,
	FOREIGN KEY (price_id) REFERENCES prices(id) ON DELETE CASCADE
) ENGINE=InnoDB;
