ALTER TABLE notes DROP hidden;
CREATE TABLE IF NOT EXISTS note_categories(
    id INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) UNIQUE NOT NULL,
    hidden BOOLEAN DEFAULT FALSE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS note_categories_assoc(
    id INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    note INTEGER UNSIGNED NOT NULL,
    category INTEGER UNSIGNED NOT NULL,
    UNIQUE(note, category),
    FOREIGN KEY (note) REFERENCES notes (id) ON DELETE CASCADE,
    FOREIGN KEY (category) REFERENCES note_categories (id) ON DELETE CASCADE
) ENGINE=InnoDB;

