HOST = "{IP}"
USERNAME = "root"
PASSWORD = "toor"
DBNAME = "enibar"

DEBUG = False
ECOCUP_PRICE = 1.0
IMG_BASE_DIR = "img/"

ASK_VALIDATION_VALIDATE = True
ASK_VALIDATION_REFILL = True
MAX_HISTORY = 5

AGIO_THRESHOLD = 14
AGIO_EVERY = 7
AGIO_PERCENT = 5.0

ECOCUP_PRICE = 1.0
ECOCUP_CATEGORY = "Bar"
ECOCUP_PRICE_TYPES = {'take': "Achat", 'repay': "Remboursement"}
ECOCUP_NAME = "Ecocup"
